package RLML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Actions = 0;
  public static final int ActorCritic = 1;
  public static final int CPG_ES = 2;
  public static final int DQN = 3;
  public static final int DoneStates = 4;
  public static final int Environment = 5;
  public static final int EvolutionStrategies = 6;
  public static final int GeneticAlgorithm = 7;
  public static final int Geneticparameters = 8;
  public static final int GradientFree = 9;
  public static final int HyperNEAT = 10;
  public static final int Hyperparameters = 11;
  public static final int MonteCarloControl = 12;
  public static final int ProximalPolicyOptimization = 13;
  public static final int QLearning = 14;
  public static final int RLAgent = 15;
  public static final int RLAlgorithm = 16;
  public static final int RLML = 17;
  public static final int RLMLComparator = 18;
  public static final int Result = 19;
  public static final int Rewards = 20;
  public static final int SARSA = 21;
  public static final int Settings = 22;
  public static final int States = 23;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L);
    builder.put(0x1d76fb9dad847c98L, Actions);
    builder.put(0x42c2fdc337c72df2L, ActorCritic);
    builder.put(0x1867f34b87faf694L, CPG_ES);
    builder.put(0x41f9d76e6f0c3626L, DQN);
    builder.put(0x7adf9c592617f60eL, DoneStates);
    builder.put(0x4613d414d7bcd92aL, Environment);
    builder.put(0x1867f34b864e72c1L, EvolutionStrategies);
    builder.put(0x1867f34b857b362aL, GeneticAlgorithm);
    builder.put(0x1867f34b858fee2eL, Geneticparameters);
    builder.put(0x1867f34b857b33a9L, GradientFree);
    builder.put(0x1867f34b87faf641L, HyperNEAT);
    builder.put(0x6166013d0c7aea5cL, Hyperparameters);
    builder.put(0x42c2fdc337cf3064L, MonteCarloControl);
    builder.put(0x2a1c7ed924494d03L, ProximalPolicyOptimization);
    builder.put(0x3a3770586b503ad3L, QLearning);
    builder.put(0x4613d414d7bcd92bL, RLAgent);
    builder.put(0x6166013d0c7ae9d6L, RLAlgorithm);
    builder.put(0x4613d414d7bcd8f1L, RLML);
    builder.put(0x2a1c7ed924a475deL, RLMLComparator);
    builder.put(0x4613d414d7bcd92cL, Result);
    builder.put(0x49c190188964fa77L, Rewards);
    builder.put(0x6166013d0c7aea76L, SARSA);
    builder.put(0x6166013d0c7aea5bL, Settings);
    builder.put(0x1d76fb9dad847c95L, States);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
