package RLML.editor;

/*Generated by MPS */

import javax.swing.JComponent;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JButton;
import java.text.DecimalFormat;
import org.jetbrains.mps.openapi.module.SModule;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.module.SRepository;
import RLML.util.RunProgram;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.awt.Font;
import jetbrains.mps.nodeEditor.EditorSettings;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class ButtonFactory {
  public static JComponent createRunProgramButton(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Run Program", new Runnable() {
      @Override
      public void run() {

        final DecimalFormat df = new DecimalFormat("#.##");
        SModule module = SNodeOperations.getModel(node).getModule();

        SRepository repository = editorContext.getRepository();

        StringBuilder str = RunProgram.runMyProgram(node, repository);
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value$tVy0, str.toString());
      }
    });
    return button;
  }
  public static JComponent createClearButton(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Clear Result", new Runnable() {
      @Override
      public void run() {
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value$tVy0, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value2$7Qcj, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value3$bVkG, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value4$bVzH, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value5$cbJM, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value6$cgU8, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value7$eN1V, " ");
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.value8$eSch, " ");
      }
    });
    return button;
  }

  private static JButton createButton(final SNode node, final EditorContext editorContext, String title, final Runnable action) {
    JButton button = new JButton(title);
    button.setFont(new Font(EditorSettings.getInstance().getFontFamily(), Font.PLAIN, EditorSettings.getInstance().getFontSize()));
    button.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent p0) {
        editorContext.getRepository().getModelAccess().executeCommandInEDT(action);
      }
    });
    return button;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink result$uOrF = MetaAdapterFactory.getContainmentLink(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd8f1L, 0x3a3770586b503fccL, "result");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$tVy0 = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x1fc7710a25a88d53L, "value");
    /*package*/ static final SProperty value2$7Qcj = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbf1eL, "value2");
    /*package*/ static final SProperty value3$bVkG = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfb1L, "value3");
    /*package*/ static final SProperty value4$bVzH = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfb2L, "value4");
    /*package*/ static final SProperty value5$cbJM = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfcdL, "value5");
    /*package*/ static final SProperty value6$cgU8 = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfceL, "value6");
    /*package*/ static final SProperty value7$eN1V = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfe1L, "value7");
    /*package*/ static final SProperty value8$eSch = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x2abf56dadd9bbfe2L, "value8");
  }
}
