package RLML.editor;

/*Generated by MPS */

import javax.swing.JComponent;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JButton;
import org.jetbrains.mps.openapi.module.SRepository;
import RLML.util.RunProgram;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import javax.swing.JTextArea;
import java.awt.Font;
import jetbrains.mps.nodeEditor.EditorSettings;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class ButtonFactory {
  public static JComponent createRunProgramButton(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Run Program", new Runnable() {
      @Override
      public void run() {

        SRepository repository = editorContext.getRepository();
        StringBuilder result = RunProgram.runMyProgram(node, repository);
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.result$tVy0, result.toString());
      }
    });
    return button;
  }
  public static JComponent createClearButton(final EditorContext editorContext, final SNode node) {
    JButton button = ButtonFactory.createButton(node, editorContext, "Clear Result", new Runnable() {
      @Override
      public void run() {
        SPropertyOperations.assign(SLinkOperations.getTarget(node, LINKS.result$uOrF), PROPS.result$tVy0, " ");
      }
    });
    return button;
  }

  public static JTextArea createResultArea(final SNode node) {
    JTextArea textArea = new JTextArea(SPropertyOperations.getString(node, PROPS.result$tVy0));
    textArea.setEditable(false);
    return textArea;

  }

  private static JButton createButton(final SNode node, final EditorContext editorContext, String title, final Runnable action) {
    JButton button = new JButton(title);
    button.setFont(new Font(EditorSettings.getInstance().getFontFamily(), Font.PLAIN, EditorSettings.getInstance().getFontSize()));
    button.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent p0) {
        editorContext.getRepository().getModelAccess().executeCommandInEDT(action);
      }
    });
    return button;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink result$uOrF = MetaAdapterFactory.getContainmentLink(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd8f1L, 0x3a3770586b503fccL, "result");
  }

  private static final class PROPS {
    /*package*/ static final SProperty result$tVy0 = MetaAdapterFactory.getProperty(0x3c2f74fb565a4cb8L, 0x8a8142024cc7aa10L, 0x4613d414d7bcd92cL, 0x1fc7710a25a88d53L, "result");
  }
}
